/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PaymentMethodRouteImport } from './routes/payment-method'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodRoute = PaymentMethodRouteImport.update({
  id: '/payment-method',
  path: '/payment-method',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/payment': typeof PaymentRoute
  '/payment-method': typeof PaymentMethodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/payment': typeof PaymentRoute
  '/payment-method': typeof PaymentMethodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/payment': typeof PaymentRoute
  '/payment-method': typeof PaymentMethodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/confirm' | '/payment' | '/payment-method'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/confirm' | '/payment' | '/payment-method'
  id: '__root__' | '/' | '/confirm' | '/payment' | '/payment-method'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmRoute: typeof ConfirmRoute
  PaymentRoute: typeof PaymentRoute
  PaymentMethodRoute: typeof PaymentMethodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-method': {
      id: '/payment-method'
      path: '/payment-method'
      fullPath: '/payment-method'
      preLoaderRoute: typeof PaymentMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmRoute: ConfirmRoute,
  PaymentRoute: PaymentRoute,
  PaymentMethodRoute: PaymentMethodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
